use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{Implementation, ServerCapabilities, ServerConfig};
use rmcp::{Peer, RoleServer, ServiceExt, tool_handler};
use ws_broker::Reader;
use ws_config::Mode;
use ws_policy::{Denial, Guard, TicketId};

use crate::action::{Action, perform};
use crate::consent;

const COMMON: &str = "Unofficial Wealthsimple tools. Amounts are decimal strings with a currency. \
    Accounts can be given by nickname or type, such as `tfsa`, and securities by ticker, such as `XEQT`. \
    Signing in happens only in a terminal (`ws-mcp login`). Never ask the user for credentials or codes.";

const READ: &str = "Read mode: accounts, positions, activities, quotes, and orders come from the user's real \
    account, and there are no order tools.";

const PAPER: &str = "Paper mode: orders are simulated against live quotes. Positions, activities, and orders \
    show the simulation, not the real account.";

const TRADE: &str = "Trade mode: orders go to the user's real Wealthsimple account.";

const ORDERS: &str = "To trade, call preview_order, show the user the order and its estimated value, and call \
    place_order with the ticket only after they confirm. Tickets work once and expire. If a ticket needs approval, \
    place_order may ask the user to approve it in the chat. If it is refused as needing approval, ask the user to \
    run `ws-mcp approve <ticket>` in their own terminal or approve it on `ws-mcp dashboard`. Never run it yourself. Keep the key from \
    place_order to check the order with order_status or cancel it with cancel_order.";

#[derive(Clone)]
pub struct Server {
    reader: Arc<dyn Reader>,
    guard: Option<Arc<Guard>>,
    tool_router: ToolRouter<Self>,
}

impl Server {
    #[must_use]
    pub fn new(reader: Arc<dyn Reader>, guard: Option<Arc<Guard>>) -> Self {
        let tool_router = match guard {
            Some(_) => Self::read_router() + Self::trade_router(),
            None => Self::read_router(),
        };
        Self { reader, guard, tool_router }
    }

    pub(crate) async fn answer<A: Action<Context = dyn Reader>>(&self, action: A) -> Result<String, String> {
        perform(action, self.reader.as_ref()).await.map_err(|e| e.to_string())
    }

    pub(crate) async fn act<A: Action<Context = Guard>>(&self, action: A) -> Result<String, String> {
        let Some(guard) = &self.guard else { return Err(Denial::ReadOnly.to_string()) };
        perform(action, guard).await.map_err(|e| e.to_string())
    }

    pub(crate) async fn consent(&self, peer: &Peer<RoleServer>, ticket: &TicketId) -> Result<(), String> {
        let Some(guard) = &self.guard else { return Ok(()) };
        consent::ask(guard, peer, ticket).await.map_err(|e| e.to_string())
    }

    fn instructions(&self) -> String {
        match self.guard.as_deref().map(Guard::mode) {
            None | Some(Mode::Read) => format!("{COMMON} {READ}"),
            Some(Mode::Paper) => format!("{COMMON} {PAPER} {ORDERS}"),
            Some(Mode::Trade) => format!("{COMMON} {TRADE} {ORDERS}"),
        }
    }

    pub async fn run(self) -> anyhow::Result<()> {
        let service = self.serve(rmcp::transport::stdio()).await?;
        service.waiting().await?;
        Ok(())
    }
}

#[allow(clippy::unused_async_trait_impl, reason = "the async fns are generated by `tool_handler`")]
#[tool_handler(router = self.tool_router)]
impl rmcp::ServerHandler for Server {
    fn get_info(&self) -> ServerConfig {
        ServerConfig::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("ws-mcp", env!("CARGO_PKG_VERSION")))
            .with_instructions(self.instructions())
    }
}

#[cfg(test)]
mod tests {
    use rmcp::model::{
        CallToolRequestParams, ClientConfig, ElicitRequestParams, ElicitResult, ElicitationAction,
        ElicitationCapability,
    };
    use rmcp::service::{RequestContext, RunningService};
    use rmcp::{ClientHandler, RoleClient};
    use serde_json::json;
    use ws_common::fixtures::Scratch;
    use ws_core::fixtures;

    use super::*;
    use crate::fake::{self, Market};
    use crate::home::Home;
    use crate::read::Read;
    use crate::trade::Trade;

    /// With an answer, the client can show approval prompts and gives that answer to every one.
    #[derive(Clone, Default)]
    struct Client {
        answer: Option<bool>,
    }

    impl ClientHandler for Client {
        fn get_info(&self) -> ClientConfig {
            let mut config = ClientConfig::default();
            if self.answer.is_some() {
                config.capabilities.elicitation = Some(ElicitationCapability::default());
            }
            config
        }

        fn create_elicitation(
            &self,
            _: ElicitRequestParams,
            _: RequestContext<RoleClient>,
        ) -> impl Future<Output = Result<ElicitResult, rmcp::ErrorData>> + Send + '_ {
            std::future::ready(Ok(match self.answer {
                Some(approve) => ElicitResult::new(ElicitationAction::Accept).with_content(json!({"approve": approve})),
                None => ElicitResult::new(ElicitationAction::Decline),
            }))
        }
    }

    async fn serve(server: Server, client: Client) -> RunningService<RoleClient, Client> {
        let (server_end, client_end) = tokio::io::duplex(64 * 1024);
        tokio::spawn(async move {
            if let Ok(running) = server.serve(server_end).await {
                let _ = running.waiting().await;
            }
        });
        client.serve(client_end).await.unwrap_or_else(|e| panic!("{e}"))
    }

    async fn connect() -> RunningService<RoleClient, Client> {
        serve(Server::new(Arc::new(Market), None), Client::default()).await
    }

    async fn paper(scratch: &Scratch) -> RunningService<RoleClient, Client> {
        chatty(scratch, "", Client::default()).await
    }

    async fn chatty(scratch: &Scratch, limits: &str, client: Client) -> RunningService<RoleClient, Client> {
        let (paper, guard) = fake::configured(&Home::at(scratch.dir()), limits);
        serve(Server::new(paper, Some(guard)), client).await
    }

    fn order(shares: &str, limit: &str) -> serde_json::Value {
        json!({
            "account": "Main", "security": fixtures::security(), "side": "buy",
            "shares": shares, "limit": limit,
        })
    }

    fn parsed(text: &str) -> serde_json::Value {
        serde_json::from_str(text).unwrap_or_else(|e| panic!("{e}: {text}"))
    }

    async fn call(
        client: &RunningService<RoleClient, Client>,
        tool: &'static str,
        args: serde_json::Value,
    ) -> Result<(bool, String), rmcp::ServiceError> {
        let mut params = CallToolRequestParams::new(tool);
        if let Some(args) = args.as_object() {
            params = params.with_arguments(args.clone());
        }
        let result = client.call_tool(params).await?;
        let text = result.content.first().and_then(|c| c.as_text()).map(|t| t.text.clone()).unwrap_or_default();
        Ok((result.is_error == Some(true), text))
    }

    fn commands<S: clap::Subcommand>() -> Vec<String> {
        S::augment_subcommands(clap::Command::new("ws-mcp"))
            .get_subcommands()
            .map(|c| c.get_name().replace('-', "_"))
            .collect()
    }

    async fn tool_names(client: &RunningService<RoleClient, Client>) -> Vec<String> {
        let tools = client.list_all_tools().await.unwrap_or_else(|e| panic!("{e}"));
        let mut names: Vec<String> = tools.iter().map(|t| t.name.to_string()).collect();
        names.sort_unstable();
        names
    }

    #[tokio::test]
    async fn read_mode_offers_exactly_the_cli_read_commands_all_read_only() {
        let client = connect().await;
        let mut expected = commands::<Read>();
        expected.sort_unstable();
        assert_eq!(tool_names(&client).await, expected);
        let tools = client.list_all_tools().await.unwrap_or_else(|e| panic!("{e}"));
        assert!(tools.iter().all(|t| t.annotations.as_ref().and_then(|a| a.read_only_hint) == Some(true)));
    }

    #[tokio::test]
    async fn paper_mode_adds_the_cli_order_commands_and_limits_status() {
        let scratch = Scratch::new();
        let client = paper(&scratch).await;
        let mut expected = [commands::<Read>(), commands::<Trade>(), vec!["limits_status".to_owned()]].concat();
        expected.sort_unstable();
        assert_eq!(tool_names(&client).await, expected);
    }

    #[tokio::test]
    async fn previews_places_and_tracks_a_paper_order_once() {
        let scratch = Scratch::new();
        let client = paper(&scratch).await;
        let reply = |tool, args| {
            let client = &client;
            async move { call(client, tool, args).await.unwrap_or_else(|e| panic!("{e}")) }
        };

        let (failed, text) = reply("preview_order", order("2", "40")).await;
        assert!(!failed, "{text}");
        let ticket = parsed(&text);
        assert_eq!((ticket["value"]["amount"].as_str(), ticket["approval"].as_str()), (Some("80"), Some("not_needed")));

        let (failed, text) = reply("place_order", json!({"ticket_id": ticket["id"]})).await;
        assert!(!failed, "{text}");
        let receipt = parsed(&text);
        assert_eq!(receipt["key"], ticket["key"]);

        let (failed, text) = reply("order_status", json!({"key": receipt["key"]})).await;
        assert!(!failed, "{text}");
        assert_eq!(parsed(&text)["status"], "filled");

        let (failed, text) = reply("place_order", json!({"ticket_id": ticket["id"]})).await;
        assert!(failed && text.contains("already used"), "{text}");

        let status = parsed(&reply("limits_status", json!({})).await.1);
        assert_eq!((status["mode"].as_str(), status["orders_today"].as_u64()), (Some("paper"), Some(1)));
    }

    #[tokio::test]
    async fn large_orders_wait_for_approval_in_a_terminal() {
        let scratch = Scratch::new();
        let client = paper(&scratch).await;
        let (_, text) = call(&client, "preview_order", order("10", "40")).await.unwrap_or_else(|e| panic!("{e}"));
        let ticket = parsed(&text);
        assert_eq!(ticket["approval"], "pending");
        let (failed, text) =
            call(&client, "place_order", json!({"ticket_id": ticket["id"]})).await.unwrap_or_else(|e| panic!("{e}"));
        assert!(failed && text.contains("ws-mcp approve"), "{text}");
    }

    #[tokio::test]
    async fn large_orders_are_approved_in_the_chat_only_when_allowed_and_accepted() {
        let large = order("10", "40");
        for (limits, answer, placed) in [
            ("approve_in_chat = true", Some(true), true),
            ("approve_in_chat = true", Some(false), false),
            ("approve_in_chat = true", None, false),
            ("", Some(true), false),
        ] {
            let scratch = Scratch::new();
            let client = chatty(&scratch, limits, Client { answer }).await;
            let (_, text) = call(&client, "preview_order", large.clone()).await.unwrap_or_else(|e| panic!("{e}"));
            let ticket = parsed(&text);
            let (failed, text) = call(&client, "place_order", json!({"ticket_id": ticket["id"]}))
                .await
                .unwrap_or_else(|e| panic!("{e}"));
            assert_eq!(!failed, placed, "{limits} {answer:?}: {text}");
        }
    }

    #[tokio::test]
    async fn the_kill_switch_and_malformed_orders_stop_previews() {
        let scratch = Scratch::new();
        let client = paper(&scratch).await;
        let both = json!({
            "account": "tfsa", "security": fixtures::security(), "side": "buy", "shares": "1", "amount": "40",
        });
        let (failed, text) = call(&client, "preview_order", both).await.unwrap_or_else(|e| panic!("{e}"));
        assert!(failed && text.contains("exactly one of shares or amount"), "{text}");

        ws_common::write(&scratch.path("KILL"), b"").unwrap_or_else(|e| panic!("{e}"));
        let (failed, text) = call(&client, "preview_order", order("1", "40")).await.unwrap_or_else(|e| panic!("{e}"));
        assert!(failed && text.contains("kill switch"), "{text}");
    }

    #[tokio::test]
    async fn returns_domain_data_as_json() {
        let client = connect().await;
        let (failed, text) = call(&client, "accounts", json!(null)).await.unwrap_or_else(|e| panic!("{e}"));
        assert!(!failed);
        let accounts: serde_json::Value = serde_json::from_str(&text).unwrap_or_else(|e| panic!("{e}"));
        assert_eq!(accounts[0]["id"], fixtures::account().as_str());
        assert_eq!(accounts[0]["nickname"], "Main");
    }

    #[tokio::test]
    async fn refuses_names_that_match_nothing() {
        let client = connect().await;
        let (failed, text) =
            call(&client, "quote", json!({"security": "AAPL"})).await.unwrap_or_else(|e| panic!("{e}"));
        assert!(failed);
        assert!(text.contains("no security with the ticker AAPL"), "{text}");
        let (failed, text) =
            call(&client, "positions", json!({"account": "rrsp"})).await.unwrap_or_else(|e| panic!("{e}"));
        assert!(failed && text.contains("no account called rrsp"), "{text}");
    }

    #[tokio::test]
    async fn reports_broker_errors_as_tool_errors() {
        let client = connect().await;
        let reply = |tool, args| {
            let client = &client;
            async move { call(client, tool, args).await.unwrap_or_else(|e| panic!("{e}")) }
        };
        assert_eq!(reply("quote", json!({"security": "sec-s-x"})).await, (true, "sec-s-x not found".to_owned()));
        assert_eq!(reply("activities", json!({"account": "main", "limit": 1000})).await.1, "limit 100 not found");
    }
}
