[package]
name = "ws-config"
description = "Typed runtime configuration"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ws-core.workspace = true
ws-common.workspace = true

rust_decimal.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
ws-common = { workspace = true, features = ["fixtures"] }
